name: doctest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10  # Corrected version

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pydocstyle

    - name: Lint with pydocstyle
      run: pydocstyle --convention=numpy acsefunctions/taylor.py acsefunctions/bessel.py

    - name: Run doctest
      run: |
        python -m doctest -v acsefunctions/taylor.py acsefunctions/bessel.py
